# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      ../sw/laptop.nix
    ];

  boot.initrd.luks.devices = [
    { name = "pong"; device = "/dev/sda3"; preLVM = true; }
    { name = "home"; device = "/dev/sdb1"; }
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.blacklistedKernelModules = [ "nouveau" ];
  boot.extraModulePackages = [ ];

  boot.kernelPackages = pkgs.linuxPackages_4_1 // {
    virtualbox = pkgs.linuxPackages_4_1.virtualbox.override {
      # enableExtensionPack = true;
      pulseSupport = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a12125b-48d7-4da1-83f3-af85fcf0382a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6553da13-f11b-4c28-a9fd-ee5e497aff1a";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3b91eb8e-7982-40f1-aefa-8e987c582202";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e321cbf6-7d7c-4533-8f9e-57e8882baaf6"; }
    ];

  networking.hostName = "pong";

  services.xserver.xkbOptions = "compose:ralt";
  services.xserver.videoDrivers = [ "nvidia" ];
  nix.maxJobs = 8;
}
