# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      ../sw/laptop.nix
    ];

  boot.initrd.luks.devices = [
    { name = "root"; device = "/dev/nvme0n1p3"; preLVM = true; allowDiscards = true; }
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "nvme" "usb_storage" "ahci" "i915"
  ];

  boot.kernelPackages = pkgs.linuxPackages_4_3;
  boot.extraModulePackages = [
    config.boot.kernelPackages.broadcom_sta
  ];

  boot.kernelModules = [ "kvm-intel" "brcmfmac" ];
  boot.blacklistedKernelModules = [
    "ssb" "bcma" "b43" "brcmsmac" "snd_pcsp" "pcspkr"
  ];

  boot.loader.grub.device = "/dev/nvme0n1";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/335c603c-b239-4985-8088-7ebd222ec69b";
      fsType = "ext4";
      options = "noatime,nodiratime,discard";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/f0c31a5e-3649-4cd0-b0c0-350ea9ea74ab";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/92baab4c-631d-4252-a6e3-9e639d2017eb";
      fsType = "ext4";
      options = "noatime,nodiratime,discard";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0846d1bc-3e0c-4350-a4eb-e1462aab746a"; }
    ];

  networking.hostName = "ren";

  services.xserver = {
    vaapiDrivers = [ pkgs.vaapiIntel ];
    xkbOptions = "compose:ralt,ctrl:swapcaps";
    monitorSection = ''
    DisplaySize 423 238
    '';
  };

  environment = {
    etc."X11/Xresources".text = ''
      Xcursor.theme: Adwaita

      Xft.dpi: 192
      Xft.autohint: 0
      Xft.lcdfilter:  lcddefault
      Xft.hintstyle:  hintfull
      Xft.hinting: 1
      Xft.antialias: 1
      Xft.rgba: rgb
    '';

    variables.QT_DEVICE_PIXEL_RATIO = "2";
    variables.GDK_SCALE = "2";
    variables.GDK_DPI_SCALE = "0.5";
  };

  nix.maxJobs = 4;
}
